#!/usr/bin/env python3
"""Generate frontend/data/resources.js from the markdown files under resources/.

Source of truth is resources/<category>/<slug>.md (one level up from
frontend/). This script walks that tree, extracts frontmatter + H1 + body,
and bakes everything into frontend/data/resources.js which the dashboard
loads as a regular <script> tag (so it works under file:// without fetch).
Run from the repo root after editing any markdown:

    python3 frontend/scripts/build-resources.py

Categories are auto-discovered from `resources/*/` directory listings. The
display name is derived from the slug ("local-models" -> "Local models")
unless overridden in the optional `resources/_categories.json` map. That
file is plain JSON keyed by slug:

    { "mcp": "MCP", "tips-and-tricks": "Tips & tricks" }

Anything not listed there falls back to the auto-derived name.
"""
import json
import re
from pathlib import Path

SCRIPT = Path(__file__).resolve()
FRONTEND = SCRIPT.parent.parent       # frontend/
ROOT = FRONTEND.parent                # repo root
RESOURCES = ROOT / "resources"
OUT = FRONTEND / "data" / "resources.js"
CATEGORY_OVERRIDES = RESOURCES / "_categories.json"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
H1_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)


def parse_frontmatter(text: str):
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    fm: dict = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        fm[k.strip()] = v.strip()
    return fm, text[m.end():]


def parse_h1(body: str) -> str:
    m = H1_RE.search(body)
    return m.group(1).strip() if m else "(untitled)"


def auto_name(slug: str) -> str:
    """Slug -> display name. 'local-models' -> 'Local models'."""
    parts = slug.replace("_", "-").split("-")
    if not parts:
        return slug
    return " ".join([parts[0].capitalize()] + [p.lower() for p in parts[1:]])


def load_overrides() -> dict:
    if not CATEGORY_OVERRIDES.is_file():
        return {}
    try:
        return json.loads(CATEGORY_OVERRIDES.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise SystemExit(f"Invalid JSON in {CATEGORY_OVERRIDES.relative_to(ROOT)}: {e}")


def main():
    overrides = load_overrides()
    categories = []
    total_files = 0
    if RESOURCES.is_dir():
        slugs = sorted(
            d.name for d in RESOURCES.iterdir()
            if d.is_dir() and not d.name.startswith((".", "_"))
        )
        for slug in slugs:
            d = RESOURCES / slug
            display = overrides.get(slug, auto_name(slug))
            files = []
            for fp in sorted(d.glob("*.md")):
                text = fp.read_text(encoding="utf-8")
                fm, body = parse_frontmatter(text)
                files.append({
                    "path": f"{slug}/{fp.name}",
                    "slug": fp.stem,
                    "title": parse_h1(body),
                    "category": fm.get("category", display),
                    "date_added": fm.get("date_added", ""),
                    "content": body.strip(),
                })
            files.sort(key=lambda f: f["title"].lower())
            if files:
                categories.append({"slug": slug, "name": display, "files": files})
                total_files += len(files)

    payload = json.dumps({"categories": categories}, indent=2, ensure_ascii=False)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by frontend/scripts/build-resources.py - do not edit by hand.\n"
        "// Re-run `python3 frontend/scripts/build-resources.py` after editing markdown files in resources/.\n\n"
        f"window.RESOURCES = {payload};\n",
        encoding="utf-8",
    )
    rel = OUT.relative_to(FRONTEND)
    print(f"Wrote frontend/{rel}: {total_files} files across {len(categories)} categories.")


if __name__ == "__main__":
    main()
