#!/usr/bin/env python3
"""Generate docs/data/resources.js from the markdown files under resources/.

Source of truth is resources/<category>/<kind>/<slug>.md, where <kind> is
either `theory` or `practice`. This script walks that tree, extracts
frontmatter + H1 + body, and bakes everything into docs/data/resources.js
which the dashboard loads as a regular <script> tag (so it works under file://
without fetch, and from GitHub Pages serving from /docs). Run from the
repo root after editing any markdown:

    python3 docs/scripts/build-resources.py

Categories are auto-discovered from `resources/*/` directory listings. The
display name is derived from the slug ("local-models" -> "Local models")
unless overridden in the optional `resources/_categories.json` map. That
file is plain JSON keyed by slug:

    { "mcp": "MCP", "tips-and-tricks": "Tips & tricks" }

Anything not listed there falls back to the auto-derived name.
"""
import json
import re
from pathlib import Path

SCRIPT = Path(__file__).resolve()
DOCS = SCRIPT.parent.parent           # docs/
ROOT = DOCS.parent                    # repo root
RESOURCES = ROOT / "resources"
OUT = DOCS / "data" / "resources.js"
CATEGORY_OVERRIDES = RESOURCES / "_categories.json"

KINDS = ("theory", "practice")

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
H1_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)


def parse_frontmatter(text: str):
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    fm: dict = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        fm[k.strip()] = v.strip()
    return fm, text[m.end():]


def parse_h1(body: str) -> str:
    m = H1_RE.search(body)
    return m.group(1).strip() if m else "(untitled)"


def auto_name(slug: str) -> str:
    """Slug -> display name. 'local-models' -> 'Local models'."""
    parts = slug.replace("_", "-").split("-")
    if not parts:
        return slug
    return " ".join([parts[0].capitalize()] + [p.lower() for p in parts[1:]])


def load_overrides() -> dict:
    if not CATEGORY_OVERRIDES.is_file():
        return {}
    try:
        return json.loads(CATEGORY_OVERRIDES.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise SystemExit(f"Invalid JSON in {CATEGORY_OVERRIDES.relative_to(ROOT)}: {e}")


def read_doc(fp: Path, slug: str, kind: str) -> dict:
    text = fp.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(text)
    return {
        "path": f"{slug}/{kind}/{fp.name}",
        "slug": fp.stem,
        "kind": kind,
        "title": parse_h1(body),
        "date_added": fm.get("date_added", ""),
        "content": body.strip(),
    }


def main():
    overrides = load_overrides()
    categories = []
    total_files = 0
    if RESOURCES.is_dir():
        slugs = sorted(
            d.name for d in RESOURCES.iterdir()
            if d.is_dir() and not d.name.startswith((".", "_"))
        )
        for slug in slugs:
            d = RESOURCES / slug
            display = overrides.get(slug, auto_name(slug))
            files = []
            for kind in KINDS:
                kdir = d / kind
                if kdir.is_dir():
                    for fp in sorted(kdir.glob("*.md")):
                        files.append(read_doc(fp, slug, kind))
            files.sort(key=lambda f: (f["kind"], f["title"].lower()))
            if files:
                categories.append({"slug": slug, "name": display, "files": files})
                total_files += len(files)

    payload = json.dumps({"categories": categories}, indent=2, ensure_ascii=False)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by docs/scripts/build-resources.py - do not edit by hand.\n"
        "// Re-run `python3 docs/scripts/build-resources.py` after editing markdown files in resources/.\n\n"
        f"window.RESOURCES = {payload};\n",
        encoding="utf-8",
    )
    rel = OUT.relative_to(DOCS)
    print(f"Wrote docs/{rel}: {total_files} files across {len(categories)} categories.")


if __name__ == "__main__":
    main()
