#!/usr/bin/env python3
"""Generate data/resources.js from the markdown files under resources/.

Why this script exists: the dashboard runs as static HTML opened directly
from the filesystem (`file://`), so it can't fetch markdown files at
runtime. Instead, we bake the resource tree + content into a JS file that
the page loads as a regular <script>. Run this whenever you add, edit, or
move a file under resources/.

    python3 scripts/build-resources.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESOURCES = ROOT / "resources"
OUT = ROOT / "data" / "resources.js"

THEME_NAMES = {
    "frontier-models": "Frontier Models",
    "open-weights": "Open Weights",
    "agents-and-tooling": "Agents & Tooling",
    "products-and-features": "Products & Features",
    "research-and-evals": "Research & Evals",
    "business-and-infra": "Business & Infra",
    "policy-and-safety": "Policy & Safety",
}
THEME_ORDER = list(THEME_NAMES.keys())

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
H1_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)


def parse_frontmatter(text: str):
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    fm: dict = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        v = v.strip()
        if v == "true":
            fm[k.strip()] = True
        elif v == "false":
            fm[k.strip()] = False
        else:
            fm[k.strip()] = v
    return fm, text[m.end():]


def parse_h1(body: str) -> str:
    m = H1_RE.search(body)
    return m.group(1).strip() if m else "(untitled)"


def main():
    themes = []
    total_files = 0
    if RESOURCES.is_dir():
        for slug in THEME_ORDER:
            d = RESOURCES / slug
            if not d.is_dir():
                continue
            files = []
            for fp in sorted(d.glob("*.md")):
                text = fp.read_text(encoding="utf-8")
                fm, body = parse_frontmatter(text)
                files.append({
                    "path": f"{slug}/{fp.name}",
                    "slug": fp.stem,
                    "title": parse_h1(body),
                    "date": fm.get("date", ""),
                    "theme": fm.get("theme", THEME_NAMES[slug]),
                    "auto": bool(fm.get("auto", False)),
                    "content": body.strip(),
                })
            files.sort(key=lambda f: f["date"], reverse=True)
            if files:
                themes.append({"slug": slug, "name": THEME_NAMES[slug], "files": files})
                total_files += len(files)

    payload = json.dumps({"themes": themes}, indent=2, ensure_ascii=False)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/build-resources.py - do not edit by hand.\n"
        "// Re-run `python3 scripts/build-resources.py` after editing markdown files in resources/.\n\n"
        f"window.RESOURCES = {payload};\n",
        encoding="utf-8",
    )
    rel = OUT.relative_to(ROOT)
    print(f"Wrote {rel}: {total_files} files across {len(themes)} themes.")


if __name__ == "__main__":
    main()
