#!/usr/bin/env python3
"""Generate data/topics.js from the markdown files under topics/.

Source of truth is topics/<category>/<slug>.md. This script walks that tree,
extracts frontmatter + H1 + body, and bakes everything into data/topics.js
which the dashboard loads as a regular <script> tag (so it works under
file:// without fetch). Run after editing any topic markdown:

    python3 scripts/build-topics.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOPICS = ROOT / "topics"
OUT = ROOT / "data" / "topics.js"

CATEGORY_NAMES = {
    "foundations": "Foundations",
    "fine-tuning": "Fine-tuning",
    "retrieval": "Retrieval",
    "agents": "Agents",
    "mcp": "MCP",
    "local-models": "Local models",
    "new-models": "New models",
    "evaluation": "Evaluation",
    "tips-and-tricks": "Tips & tricks",
}
CATEGORY_ORDER = list(CATEGORY_NAMES.keys())

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
H1_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)


def parse_frontmatter(text: str):
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    fm: dict = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        fm[k.strip()] = v.strip()
    return fm, text[m.end():]


def parse_h1(body: str) -> str:
    m = H1_RE.search(body)
    return m.group(1).strip() if m else "(untitled)"


def main():
    categories = []
    total_files = 0
    if TOPICS.is_dir():
        for slug in CATEGORY_ORDER:
            d = TOPICS / slug
            if not d.is_dir():
                continue
            files = []
            for fp in sorted(d.glob("*.md")):
                text = fp.read_text(encoding="utf-8")
                fm, body = parse_frontmatter(text)
                files.append({
                    "path": f"{slug}/{fp.name}",
                    "slug": fp.stem,
                    "title": parse_h1(body),
                    "category": fm.get("category", CATEGORY_NAMES[slug]),
                    "date_added": fm.get("date_added", ""),
                    "content": body.strip(),
                })
            files.sort(key=lambda f: f["title"].lower())
            if files:
                categories.append({"slug": slug, "name": CATEGORY_NAMES[slug], "files": files})
                total_files += len(files)

    payload = json.dumps({"categories": categories}, indent=2, ensure_ascii=False)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/build-topics.py - do not edit by hand.\n"
        "// Re-run `python3 scripts/build-topics.py` after editing markdown files in topics/.\n\n"
        f"window.TOPICS = {payload};\n",
        encoding="utf-8",
    )
    rel = OUT.relative_to(ROOT)
    print(f"Wrote {rel}: {total_files} files across {len(categories)} categories.")


if __name__ == "__main__":
    main()
